name: Deploy ADF ARM Templates

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Stop Running ADF Pipelines (if any)
      run: |
        if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
          RESOURCE_GROUP="rg-dev"
          ADF_NAME="adf-dev"
          PARAM_FILE="./templates/parameters-dev.json"
        elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
          RESOURCE_GROUP="rg-qa"
          ADF_NAME="adf-qa"
          PARAM_FILE="./templates/parameters-qa.json"
        elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
          RESOURCE_GROUP="rg-uat"
          ADF_NAME="adf-uat"
          PARAM_FILE="./templates/parameters-uat.json"
        else
          echo "Unknown environment"
          exit 1
        fi

        RUNNING_PIPELINES=$(az datafactory pipeline-run query-by-factory \
          --resource-group $RESOURCE_GROUP \
          --factory-name $ADF_NAME \
          --filter "Status eq 'InProgress'" \
          --query "value[].runId" -o tsv)

        if [ ! -z "$RUNNING_PIPELINES" ]; then
          for RUN_ID in $RUNNING_PIPELINES; do
            echo "Stopping pipeline run with ID: $RUN_ID"
            az datafactory pipeline-run cancel \
              --resource-group $RESOURCE_GROUP \
              --factory-name $ADF_NAME \
              --run-id $RUN_ID
          done
        else
          echo "No running pipelines found."
        fi

    - name: Deploy ADF ARM Template
      run: |
        az deployment group create \
          --name ADFDeployment-${{ github.run_number }} \
          --resource-group $RESOURCE_GROUP \
          --template-file ./templates/adf-arm-template.json \
          --parameters @$PARAM_FILE

    - name: Post Deployment Validation
      run: |
        az datafactory factory show \
          --name $ADF_NAME \
          --resource-group $RESOURCE_GROUP
